// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj_5efXr0l_Jtr5jgsARHENbOCJcRAYpM',
    appId: '1:216804281220:web:b284af85cd8e6302f9ebd1',
    messagingSenderId: '216804281220',
    projectId: 'notes-50420',
    authDomain: 'notes-50420.firebaseapp.com',
    storageBucket: 'notes-50420.firebasestorage.app',
    measurementId: 'G-H58KKNXH14',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmqVSrl-TcInjo_on8abXGaDU7V9-wkqI',
    appId: '1:216804281220:android:2eb1bcb1a201c4aaf9ebd1',
    messagingSenderId: '216804281220',
    projectId: 'notes-50420',
    storageBucket: 'notes-50420.firebasestorage.app',
  );
}
